// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGqN_mVW94_3_yUMX3XrjN2vPWla0DVfs',
    appId: '1:348922347003:web:d11b8c973012c1739f5f5e',
    messagingSenderId: '348922347003',
    projectId: 'homeservice-93f33',
    authDomain: 'homeservice-93f33.firebaseapp.com',
    storageBucket: 'homeservice-93f33.firebasestorage.app',
    measurementId: 'G-KK9LB9P3VP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0IVRQ4pbM8rZd1wuj4Vr9sc7Z_EgJobg',
    appId: '1:348922347003:android:9c2b078a069e79c79f5f5e',
    messagingSenderId: '348922347003',
    projectId: 'homeservice-93f33',
    storageBucket: 'homeservice-93f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAww1rP5-1m6vJr5AqSOBrHVt-DK7CU-dY',
    appId: '1:348922347003:ios:452d253450a205fc9f5f5e',
    messagingSenderId: '348922347003',
    projectId: 'homeservice-93f33',
    storageBucket: 'homeservice-93f33.firebasestorage.app',
    iosBundleId: 'com.example.homeservice',
  );
}
